version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=test_password
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_PORT=5432
      - NODE_ENV=development
