###GET /users
GET http://localhost:5000/users/all

###GET /users?email=<email>

GET http://localhost:5000/users?email=test3@exampqlqe.com


###DELETE /users
DELETE http://localhost:5000/users

###POST /users
POST http://localhost:5000/users
Content-Type: application/json

{
  "email": "test3@exampqlqe.com"
}

###PUT /users
PUT http://localhost:5000/users
Content-Type: application/json

{
  "email": "test3@exampqlqe.com",
  "firstName": "Test",
  "lastName": "User",
  "password": "pass1244P"
}

###GET /users/:hash

GET http://localhost:5000/users/34115ff931acccdd20d3f89db5cb890aeeb4fe6f