openapi: "3.0.0"
info:
  title: Meter - A Revolution Backed by Energy
  version: "1.0.0"
  contact:
    name: Support
    email: support@meter.dev
servers:
  - url: http://localhost:5000/
    description: Local Development Server
tags:
  - name: Users
    description: User-related endpoints
paths:
  /users:
    get:
      tags:
        - Users
      summary: Returns the details of the user based on the user's email
      description: Returns the details of the user based on the user's email
      parameters:
        - name: email
          in: query
          description: The email of the user
          required: true
          schema:
            type: string
            format: email
      responses:
        "200":
          description: User Details Retrieved
          $ref: "#/components/responses/ResponseBody"
    post:
      tags:
        - Users
      summary: Register a new User with the provided email
      description: Register a new User with the provided email
      requestBody:
        description: Request Body to create new User
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                type: string
                format: email
  /users/v2:
    get:
      tags:
        - Users
      summary: Returns the details of all the registered users
      description: Returns the details of all the registered users
      responses:
        "200":
          description: User Details Retrieved
          $ref: "#/components/responses/ResponseBody"
components:
  responses:
    ResponseBody:
      content:
        application/json:
          schema:
            properties:
              error:
                description: Success/Error Status
                type: boolean
              message:
                description: Response Message
                type: string
              payload:
                description: Response payload
                type: object
